name: Kustomize development overlay update

on:
  workflow_dispatch:

jobs:
  create-pr:
    uses: Ki-Insurance/github-workflows/.github/workflows/r-update-kustomize-images.yaml@v0.0.1
    with:
      overlay: k8s/environments/development
      images: '[{"name":"my-app", "newTag": "1.4.2"}]'
      git_author_name: "<author name>"
      git_author_email: "<author email>"
      create_pr: false